//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "malicious_prompts")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub prompt_id: Uuid,
    pub user_id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub prompt: String,
    pub attack_type: String,
    pub requested_at: DateTime,
    #[sea_orm(
        belongs_to,
        from = "user_id",
        to = "user_id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub user: HasOne<super::user::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
